### ISSUE TITLE
Supporting v0.1.1 and upcoming releases

### ISSUE THREAD

**Issue by lissyx** [RustAudio/deepspeech-rs#1]
It's great that there is a Rust binding, however it seems to target v0.1.0. We did a lot of changes now, v0.1.1 is available and current master branch has also a lot of new shining.

Do you have any plan on pushing updates? How can we be of help?

**Comment by est31** [comment]
Yes, I definitely intend to support future releases. I'm looking forward to many improvements! Regarding the 0.1.1 update, I have done it locally but then didn't upload it to GitHub. Apparently not to crates.io either. Now I don't have access to the computer for a while. I think I'll re-do it locally.

> How can we be of help?

It'd be really helpful if the C++ API of the library stayed [bindgen](https://github.com/rust-lang-nursery/rust-bindgen)-compatible, that is not requiring too advanced C++ features like extending a class or similar in order to use the API... basically allowing me to bind to the library from Rust directly, without a C++ layer. The 0.1.0 and 0.1.1 APIs are fine, just to keep this in mind for future API evolution.

Also, it would be helpful to have the main library separate from libsox as this library uses the pure Rust `audrey`  crate instead that has great decoding and resampling capabilities.

I have heard about the 0.1.1 release from the fosdem talk, but it would be cool to be notified of future releases. Maybe you could file an issue here, or push an update to an issue in the deepspeech repo? I am okay with both!

**Comment by lissyx** [comment]
> It'd be really helpful if the C++ API of the library stayed bindgen-compatible, that is not requiring too advanced C++ features like extending a class or similar in order to use the API... basically allowing me to bind to the library from Rust directly, without a C++ layer. The 0.1.0 and 0.1.1 APIs are fine, just to keep this in mind for future API evolution.

It's likely we have the same requirement with SWIG for the Python and Node modules :)

> Also, it would be helpful to have the main library separate from libsox as this library uses the pure Rust audrey crate instead that has great decoding and resampling capabilities.

There's no code depending on sox in `deepspeech.cc`/`deepspeech.h`, it's all handled client-side, so I'm not sure what you are referring to there.

> I have heard about the 0.1.1 release from the fosdem talk, but it would be cool to be notified of future releases. Maybe you could file an issue here, or push an update to an issue in the deepspeech repo? I am okay with both!

We are pushing releases and tags already. I'm not sure keeping an issue open for that makes sense. For now, we can keep opening issues to you, though, but that might not scale very well :)

**Comment by est31** [comment]
I've updated to 0.1.1 in commit ac517f0a882f0c3c3d5fc99391898b32cb70d4f7
